title: "BSides Portland 2017"
author: "BSides PDX"
description: "The Northwest's Premier Security Conference"
more: "read more Â»"
url: "https://atomicu.github.io"
#baseurl: "/contrast" # comment out if in root directory

comments:
# disqus: "niklasbuschmann"
#  isso: "comments.mysite.org"

style:
  body: 'white'
  margin: 0%
  padding: 30%
  nav: "#222"
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  uppercase: true

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/atomicu/", square: true}
#  - reddit: {url: "https://www.reddit.com/user/me/", square: true}
  - twitter: {url: "https://twitter.com/bsidespdx/", square: true}
#  - facebook: {url: "https://www.facebook.com/me", square: true}
#  - google-plus: {url: "https://plus.google.com/+me", square: true}
#  - youtube: {url: "https://www.youtube.com/user/me", square: true}
#  - tumblr: {url: "http://me.tumblr.com/", square: true}
#  - steam: {url: "http://steamcommunity.com/id/me/", square: true}

paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
permalink: pretty
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: false}}]
plugins: [jekyll-feed, jekyll-paginate] # include feed plugin (supported by gh-pages)
